### ISSUE TITLE
Broken test in Intellij IDEA 2016.2

### ISSUE THREAD

**Issue by kamikat** [kamikat/moshi-jsonapi#18]
All tests in `PrivateAndProtectedTest` failed when running test from Intellij IDEA:

```
java.lang.NullPointerException: source

	at java.util.Objects.requireNonNull(Objects.java:228)
	at java.util.Scanner.<init>(Scanner.java:578)
	at moe.banana.jsonapi2.TestResources.readResource(TestResources.java:8)
	at moe.banana.jsonapi2.TestResources.getPrivateSample(TestResources.java:13)
	at moe.banana.jsonapi2.PrivateAndProtectedTest.deserializePrivatePrimitives(PrivateAndProtectedTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

And all tests passed when running from command line.

**Comment by mreichelt** [comment]
That was something I actually fiddled a lot with. The tests run fine from the command line because the classpath is resolved correctly (adding src/test/resources).
In IntelliJ, you can temporarily solve this by changing the project settings and adding the folder as a dependency:

<img width="970" alt="bildschirmfoto 2016-09-08 um 09 12 35" src="https://cloud.githubusercontent.com/assets/400322/18340340/a943c7b2-75a4-11e6-949b-738032f9bb65.png">

I would love to see a build.gradle-based solution here. I already searched a lot about this, but didn't get a fix yet. I'll write a StackoverFlow post to ask for help.

**Comment by mreichelt** [comment]
I posted a [StackOverflow question](http://stackoverflow.com/questions/39386028/intellij-tests-fail-gradle-tests-fine-does-not-recognize-json-files-in-test-r) to get an answer.

**Comment by kamikat** [comment]
It works again after upgrade to IDEA 2016.2.4.
